- hosts: ubuntu
  gather_facts: True
  gather_subset: network
  become: yes
  roles: 
    - role: networkint
      network_ifaces:
      - device: ens3
        bootproto: static 
        ip: 192.168.30.36
        netmask: 255.255.255.0
        type: ethernet
        gateway: 192.168.30.1
        dns:
         - 8.8.8.8
         - 8.8.4.4 
      - device: ens4
        bootproto: static
        ip: 192.168.20.199
        netmask: 255.255.255.0
        type: ethernet

      

