- name: Restarting Network for Centos 7
  become: yes
  systemd: name=network state=restarted
- name: Restarting Network for Ubuntu
  become: yes
  systemd:
    name: networking
    state: restarted
- name: Disable Network manager Centos
  become: yes
  systemd:
    name: NetworkManager
    state: stopped
    enabled: no
    
- name: Disable Network manager Ubuntu
  become: yes
  systemd:
    name: network-manager
    state: stopped
    enabled: no    
   